// ═══ CITY DATABASE v3 — constructionCost unificado + pollutionSensitive ═══
window.cityBuildings = {
    prefeitura: {
        name: 'Prefeitura',
        icon: '🏛️',
        category: 'admin',
        era: 0,
        unique: true,
        constructionCost: {},
        capacity: 0,
        workers: 0,
        happinessBonus: 5,
        description: 'Centro administrativo. +5 felicidade.',
    },
    casa_simples: {
        name: 'Casa Simples',
        icon: '🏠',
        category: 'moradia',
        era: 0,
        woodEra: true,               // Bloqueada após limite da Era da Madeira
        constructionCost: { gold: 50, tabua_madeira: 30 },
        pollutionSensitive: true,
        capacity: 4,
        workers: 0,
        description: 'Abriga 4 moradores.',
    },
    casa_media: {
        name: 'Casa Média',
        icon: '🏡',
        category: 'moradia',
        era: 1,
        constructionCost: { gold: 150, tabua_madeira: 50, chapa_aco: 10 },
        pollutionSensitive: true,
        capacity: 8,
        workers: 0,
        description: 'Abriga 8 moradores. Requer aço.',
    },
    campo_graos: {
        name: 'Campo de Grãos',
        icon: '🌾',
        category: 'comida',
        era: 0,
        constructionCost: { gold: 30, tabua_madeira: 15 },
        workers: 2,
        output: 'graos',
        outputRate: 6,
        description: 'Produz grãos. Requer 2 trabalhadores.',
    },
    rancho: {
        name: 'Rancho',
        icon: '🐄',
        category: 'comida',
        era: 0,
        constructionCost: { gold: 60, tabua_madeira: 25 },
        workers: 3,
        input: 'graos',
        inputRate: 2,
        output: 'carne',
        outputRate: 3,
        description: 'Converte grãos em carne. +10 felicidade se ativo.',
    },
    armazem_comida: {
        name: 'Armazém de Comida',
        icon: '🏚️',
        category: 'logistica',
        era: 0,
        constructionCost: { gold: 40, tabua_madeira: 20 },
        workers: 0,
        storageBonus: 200,
        description: '+200 armazenamento de alimentos.',
    },
    praca: {
        name: 'Praça',
        icon: '⛲',
        category: 'lazer',
        era: 0,
        constructionCost: { gold: 40, tabua_madeira: 20 },
        workers: 0,
        happinessBonus: 8,
        description: 'Ponto de encontro. +8 felicidade.',
    },
    taverna: {
        name: 'Taverna',
        icon: '🍺',
        category: 'lazer',
        era: 0,
        constructionCost: { gold: 80, tabua_madeira: 35 },
        workers: 1,
        happinessBonus: 12,
        description: 'Diversão para os trabalhadores. +12 felicidade. 1 trabalhador.',
    },
    parque: {
        name: 'Parque',
        icon: '🌳',
        category: 'lazer',
        era: 0,
        constructionCost: { gold: 100, tabua_madeira: 40, madeira_bruta: 20 },
        pollutionSensitive: true,
        workers: 0,
        happinessBonus: 10,
        migrationBonus: 0.2,
        description: 'Área verde. +10 felicidade. Atrai moradores mais rápido.',
    },
    escola: {
        name: 'Escola',
        icon: '🏫',
        category: 'educacao',
        era: 2,
        constructionCost: { gold: 200, tijolo_barro: 15, vidro: 10 },
        luxuryBuilding: true,
        pollutionSensitive: true,
        workers: 2,
        happinessBonus: 5,
        researchRate: 2,
        description: 'Gera pesquisa. +5 felicidade. 2 trabalhadores.',
    },

    grande_escola: {
        name: 'Grande Escola',
        icon: '🎓',
        category: 'educacao',
        era: 2,
        constructionCost: { gold: 350, tijolo_barro: 25, vidro: 15 },
        luxuryBuilding: true,
        civicBuilding: true,
        workers: 3,
        happinessBonus: 10,
        researchRate: 5,
        workerEfficiencyBonus: 0.15,   // +15% produção de todos os trabalhadores
        description: 'Educação avançada. +15% eficiência de trabalhadores. +10 felicidade.',
    },
    hospital: {
        name: 'Hospital',
        icon: '🏥',
        category: 'saude',
        era: 1,
        constructionCost: { gold: 300, tabua_madeira: 60, chapa_aco: 15 },
        pollutionSensitive: true,
        workers: 3,
        happinessBonus: 15,
        migrationBonus: 0.3,
        description: 'Saúde pública. +15 felicidade. Atrai moradores.',
    },

    casa_alvenaria: {
        name: 'Casa de Alvenaria',
        icon: '🧱',
        category: 'moradia',
        era: 1,
        constructionCost: { gold: 150, tijolo_barro: 20 },
        brickBuilding: true,         // Resistente à poluição
        capacity: 8,
        workers: 0,
        description: 'Abriga 8 moradores. Alvenaria resistente à poluição.',
    },
    igreja: {
        name: 'Igreja / Templo',
        icon: '⛪',
        category: 'lazer',
        era: 1,
        constructionCost: { gold: 200, tijolo_barro: 30, cal: 15 },
        brickBuilding: true,
        workers: 0,
        happinessBonus: 20,
        migrationBonus: 0.4,
        description: '+20 felicidade. Atrai moradores fortemente.',
    },
    praca_monumental: {
        name: 'Praça Monumental',
        icon: '🗿',
        category: 'lazer',
        era: 2,
        constructionCost: { gold: 500, argamassa: 20 },
        brickBuilding: true,
        workers: 0,
        happinessBonus: 30,
        migrationBonus: 0.5,
        description: 'Marco civilizatório. +30 felicidade. Atrai moradores massivamente.',
    },

    teatro_romano: {
        name: 'Teatro Romano',
        icon: '🎭',
        category: 'lazer',
        era: 2,
        constructionCost: { gold: 600, pedra_polida: 30, tijolo_barro: 20 },
        brickBuilding: true,
        luxuryBuilding: true,
        civicBuilding: true,
        workers: 2,
        happinessBonus: 35,
        migrationBonus: 0.6,
        description: '+35 felicidade. Forte atração migratória. Bônus cancelado por alta poluição. Use Mármore para maximizar o efeito.',
    },
    insulae: {
        name: 'Insulae (Apartamento)',
        icon: '🏢',
        category: 'moradia',
        era: 2,
        constructionCost: { gold: 400, vigas_aco: 15, argamassa: 20 },
        brickBuilding: true,
        luxuryBuilding: true,
        capacity: 25,
        workers: 0,
        description: 'Habitação vertical. Abriga 25 moradores. Resistente à poluição.',
    },
    aqueduto: {
        name: 'Aqueduto',
        icon: '🌊',
        category: 'infraestrutura',
        era: 2,
        unique: true,
        constructionCost: { gold: 400, pedra_polida: 25, blocos_pedra: 30 },
        brickBuilding: true,
        luxuryBuilding: true,
        waterBonus: true,
        happinessBonus: 12,
        description: 'Fornece água pura à cidade. +12 felicidade. Reduz mortalidade por fome. Único.',
    },
    mercado_cidade: {
        name: 'Mercado Municipal',
        icon: '🏪',
        category: 'comercio',
        era: 0,
        constructionCost: { gold: 80, tabua_madeira: 30 },
        workers: 1,
        happinessBonus: 6,
        taxBonus: 0.5,
        description: 'Comércio local. +6 felicidade. +50% receita de imposto.',
    },
    academia: {
        name: 'Academia de Ciências',
        icon: '🔬',
        category: 'educacao',
        era: 1,
        unique: true,
        constructionCost: { gold: 500, tabua_madeira: 80, chapa_aco: 20, cobre_fino: 5 },
        pollutionSensitive: true,
        workers: 4,
        researchRate: 8,
        happinessBonus: 5,
        description: 'Pesquisa avançada. +8 pts/h. Única.',
    },
};

window.CITY_POLICY_DEFAULTS = {
    taxRate: 0,
    housingSubsidy: false,
    foodRation: false,
};

// Legado — mantido para compatibilidade. Use BALANCE.CONSUMPTION no código novo.
window.CITY_CONSUMPTION = {
    graosPerMorador:      0.5 / 3600,
    carneBonus:           10,
    starvationGracePeriod: 45,
    happinessDecayRate:   1 / 3600,
    growthRate:           0.3 / 3600,
    declineRate:          1.5 / 3600,
};
